# SPDX-License-Identifier: Apache-2.0
version: '3.7'

networks:
    fabric_test:
        external:
            name: fabric_test

services:

    peer0org1.ccskuproductstockaccount.cconsensus.com.br:
        image: cconsensus/ccskuproductstockaccount:1.0.0
        container_name: peer0org1.ccskuproductstockaccount.cconsensus.com.br
        hostname: peer0org1.ccskuproductstockaccount.cconsensus.com.br
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_VM_DOCKER_ATTACHSTDOUT=true
            - LOG_LEVEL_APP=debug
            - LOG_LEVEL_DB=info
            - LOG_LEVEL_CONSOLE=info
            - LOG_CONSOLE_STDOUT=true
            - GOPATH=/opt/gopath
            - TZ=America/Sao_Paulo
            - CHAINCODE_SERVER_ADDRESS=peer0org1.ccskuproductstockaccount.cconsensus.com.br:9997
            - CHAINCODE_ID=ccskuproductstockaccount:82a9448370182efdd10db774f06ed75499029bde367acbea94a85eb5c41a98d5
        expose:
            - 9997
        networks:
            - fabric_test

    peer0org2.ccskuproductstockaccount.cconsensus.com.br:
        image: cconsensus/ccskuproductstockaccount:1.0.0
        container_name: peer0org2.ccskuproductstockaccount.cconsensus.com.br
        hostname: peer0org2.ccskuproductstockaccount.cconsensus.com.br
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_VM_DOCKER_ATTACHSTDOUT=true
            - LOG_LEVEL_APP=debug
            - LOG_LEVEL_DB=info
            - LOG_LEVEL_CONSOLE=info
            - LOG_CONSOLE_STDOUT=true
            - GOPATH=/opt/gopath
            - TZ=America/Sao_Paulo
            - CHAINCODE_SERVER_ADDRESS=peer0org2.ccskupccskuproductstockaccountroduct.cconsensus.com.br:9997
            - CHAINCODE_ID=ccskuproductstockaccount:82a9448370182efdd10db774f06ed75499029bde367acbea94a85eb5c41a98d5
        expose:
            - 9997
        networks:
            - fabric_test
